name: Release Version
run-name: Release Version ${{ inputs.version }}
concurrency:
  group: release-new-version
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      version:
        description: Gem Version
        required: true
        type: string

env:
  GEM_VERSION: ${{ inputs.version }}

jobs:
  rubygems:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
          bundler: latest

      - run: bin/bump-version ${{ env.GEM_VERSION }}
        shell: bash

      - uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --tag v${{ env.GEM_VERSION }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: |
            Gemfile.lock
            lib/rspec/active_support/version.rb
            CHANGELOG.md
          commit-message: Bump version for ${{ env.GEM_VERSION }}
          tag: v${{ env.GEM_VERSION }}

      - run: bundle exec rake package
        shell: bash

      - name: Configure RubyGems trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v2.0.0

      - name: Push gem
        run: |
          for gem in pkg/rspec-activesupport-$GEM_VERSION*.gem ; do
            gem push "$gem" --host https://rubygems.org
          done
        shell: bash
