name: publish

on:
  push:
    branches:
      - main
      - "releases/?*-stable"
    paths: ["lib/rspec/active_support/version.rb"]

jobs:
  rubygems:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rake spec

      - uses: ryancyq/bundle-release-gem@v1

