name: Release New Version

on:
  push:
    branches: [main]
    paths: ["lib/rspec/active_support/version.rb"]

jobs:
  rubygems:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 3
    
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
          bundler-cache: true

      - run: bundle exec rake spec

      - uses: ryancyq/bundle-release-gem@v1

